### ISSUE TITLE
Issues piping stdout from dex

### ISSUE THREAD

**Issue by samtay** [dockerland/dex#58]
@briceburg not sure if you've noticed this, but I've found that piping content, e.g.
```sh
ag 'searchterms' | less
```
hangs for dex version of `ag`. This worked after I preferred my `/usr/bin/ag`. I also noticed an issue using the stdout results like so:
```sh
for f in $(ag -l 'searchterms'); do
   sed something $f
done
```
which only started working after using my normal `/usr/bin/ag`.

**Comment by briceburg** [comment]
OK this was a doozy. I refactored how tty was passed in 36a78cdd4164702907c4b8d2b4a85061a897cafa , but the `ag` image was still busted.

It turns out that `ag` behaves very badly in a container if it's not given a tty, perhaps related to https://github.com/ggreer/the_silver_searcher/issues/535 . So I've gone ahead and modified the ag image to fix this in https://github.com/dockerland/dex-dockerfiles-extra/commit/45920099a6a3fb969b2419c9e1b17daacebb21d1 , and you can now use it as before.

piping to/from other dex images (e.g. sed) seem to work fine, so I think this was an `ag` thing.
